### ISSUE TITLE
LinkError WebAssembly Instantiation, function import requires a callable

### ISSUE THREAD

**Issue by KamalOumghar-Capgemini** [aochagavia/rocket_wasm#6]
I'm getting this strange error when trying to build the project in wasm32-unknown-unknown.
I've tried the way you recommended by following the steps:
1.  cargo build --release --target wasm32-unknown-unknown
2. python post_build.py (this creates a rocket.wasm in the html folder)
3. python -m SimpleHTTPServer
Then, when i try to access localhost to see the result, i get directory listing instead of the game running. I don't know how to go directly to the gameplay.

I also tried the traditional way with: 
cargo web start --target=wasm32-unknown-unknown
Then i opened http://localhost:8000/ but i get this error:

> Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #1 module="env" function="clear_screen" error: function import requires a callable
    at <anonymous>

Do you know how to solve this issue? 
Thanks in advance.

**Comment by aochagavia** [comment]
Where are you running the http server? You need the `index.html` file in the `html` directory.

Try the following:

```
cd html
python -m SimpleHTTPServer
```

Then everything should work

**Comment by KamalOumghar-Capgemini** [comment]
Everything works fine now, thanks a lot!
